### ISSUE TITLE
Add Ruby to image by default

### ISSUE THREAD

**Issue by zahudson95** [CircleCI-Public/cimg-android#5]
The older image had Ruby installed by default: `ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]`

Is it possible to include this with the new image to keep parity with the older version?

**Comment by felicianotech** [comment]
Yes it is possible. I'm curious, would you be able to share what you use Ruby for in an Android image?

**Comment by felicianotech** [comment]
I'm not sure if we'll want to do this, as the original request by a customer was withdrawn. So I'll close this Issue.
