### ISSUE TITLE
SDK location not found

### ISSUE THREAD

**Issue by maddy10s** [CircleCI-Public/cimg-android#64]
Here is my config file which gives  error **SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/home/circleci/code/android/local.properties'.**_

I think the image already has ANDROID_HOME defined but not sure what is missing.

`
version: 2.1
jobs:
  build:
    docker:
        - image: cimg/android:2022.09-node
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: "Install ionic and Capacitor"
          command: |
            sudo npm install -g ionic capacitor
      - run:
          name: "Install npm packages"
          command: |
            npm install
            npm run build
      - run:
          name: "Add android platform"
          command: |
            ionic cap sync android
      - run:
          name: "Generate apk"
          command: |
            cd android
            chmod 777 gradlew
            sudo ./gradlew assembledebug
            mkdir -p /tmp/apk
            cp -r platforms/android/app/build/outputs/apk/debug/app-debug.apk /tmp/apk
      - store_artifacts:
          path: /tmp/apk
          destination: apks
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
  `

**Comment by JalexChen** [comment]
Hey @maddy10s - are you still running into issues here? `ANDROID_HOME` is defined in the Dockerfile - have you tried setting the path in your local properties as well? Additionally, are you able to share your build url so we can take a closer look?

**Comment by JalexChen** [comment]
Closing this out as it has almost been open for a while. Please reopen if you continue to run into this issue
