### ISSUE TITLE
Any reason why JDK 11 isn't anymore part of the latest cimg/android?

### ISSUE THREAD

**Issue by ahibrahimleague** [CircleCI-Public/cimg-android#83]
The question as the title, any reason why the `cimg/android` does [install](https://github.com/CircleCI-Public/cimg-android/blob/main/2023.05/Dockerfile#L14-L17) JDK 8 and 17 but ignores 11 (I guess it's even LTS)? 

We have a use case in the Android Gradle Plugin 8.0.0 that requires JDK 17 to run; however, due to some dependencies on a [tool](https://github.com/cashapp/paparazzi/issues/384) that we use, it has some incompatibilities with JDK 17 so we'd like to continue running the tasks relevant to this tool under JDK 11.

I guess we could use `apt-get install` to download the JDK 11, but it would be nice to provide this Java version out of the box through the docker image.

**Comment by ryanbourdais** [comment]
Closing this issue as it has gone stale.
