### ISSUE TITLE
Feature Request: ARM host images

### ISSUE THREAD

**Issue by mirokolodii** [CircleCI-Public/cimg-android#87]
**Describe the Feature Request**
There are Android emulator images with ARM architecture available on CircleCI.
As example:
` system-images;android-31;default;arm64-v8a`
In order to run them though, host should also be ARM based, while current Android host images are x86_64.

**Is your feature request related to a particular problem?**
Some of Android 3rd party libraries stopped supporting x86_64 architecture (because basically all current Android devices are ARM based, while it takes a lot of maintenance work for 3rd party library owners to continue supporting x86_64 architecture).
So, if I want to run Android automated tests (UI tests) of an app, which doesn't support x86_64 architecture, on emulator, I can only do that on ARM based emulator.

**How will this feature request benefit CircleCI jobs using this image?**
CircleCI jobs will be able to run Android automated tests of apps, which do not support x86_64 architecture.

**Describe the solution you would like to see**
I would like to have possibility to run emulator with ARM architecture, using one of Android-ready host images on CircleCI.

**Describe alternatives you have considered**
Alternative is to provide some dummy implementation for 3rd party SDK, which doesn't support x86_64 architecture, for test build variants. The side effect is that there will be difference in code between test builds and non-test builds, so tests will not be run on exactly the same codebase, which is used on real-life scenarios.

**Comment by ryanbourdais** [comment]
Hi @mirokolodii if this is in reference to the machine images you can create a feature request here on [canny](https://circleci.canny.io/images). We use this to track how much desire there is for new images. On the other hand, if this is a request for a docker ARM image for android as a response to [yesterday's announcement](https://discuss.circleci.com/t/product-launch-arm-docker-preview/48601) you can respond to [this form](https://docs.google.com/forms/d/e/1FAIpQLSdghxNBVvTnCXQjDP6D7SRr16np8PKOZ4-OJVZIIs2lJaLW-A/viewform) that we are using to help prioritize which convenience images receive arm support first.
