### ISSUE TITLE
Enable arm64 builds

### ISSUE THREAD

**Issue by BytesGuy** [CircleCI-Public/cimg-android#88]
The `emulator` package in `sdkmanager` does not support arm64 therefore the `sdkmanager "tools"` command fails on arm64 builds.

It might be possible to work around this by looking at the following:

https://developer.android.com/studio/releases/emulator#emulator_for_arm64_hosts

Working branch for arm64: https://github.com/CircleCI-Public/cimg-android/tree/arm64-support

**Comment by yogurtearl** [comment]
You can also find linux arm `emulator` binaries on the android sdk CI output: 

https://ci.android.com/builds/branches/aosp-emu-master-dev/grid?legacy=1

**Comment by yogurtearl** [comment]
See related issue here: https://issuetracker.google.com/issues/242699119
