### ISSUE TITLE
Feature Request: <Ruby for Fastlane>

### ISSUE THREAD

**Issue by Dtthatcher** [CircleCI-Public/cimg-android#89]
For our official CircleCI Docker Convenience Image support policy, please see [CircleCI docs](https://circleci.com/docs/convenience-images-support-policy).

This policy outlines the release, update, and deprecation policy for CircleCI Docker Convenience Images.

---

**Describe the Feature Request**

Our org uses Fastlane which requires Ruby.  This helps to keep our CI very similar between iOS and Android.
The Ruby install step using a CCI Ruby Orb usually takes about 3 min on android:2023.06.1 with xlarge image size
and needs to be repeated in a lot of the jobs in our workflow. 

So I would like to request an image with Ruby installed (V 2.7 is the standard) or all images have this installed.

**Is your feature request related to a particular problem?**
See above

**How will this feature request benefit CircleCI jobs using this image?**
Large reduction in time when switching jobs.

In order for us to add a tool within the image, it has to be something that is maintained and useful to a majority of CircleCI users. Every tool added makes the image larger and slower for all users, so any new additions need to be carefully thought out.

**Describe the solution you would like to see**
Either a single image with the Ruby with a quarterly update to keep up to speed with other releases, or adding Ruby to all future images.

**Describe alternatives you have considered**
Forking the repo and adding myself, but figured an official request would be better to support everyone who uses Fastlane

**Comment by ryanbourdais** [comment]
@Dtthatcher This is a feature that I will add for the August release of this image. The machine image has ruby installed in the mean time.

**Comment by Dtthatcher** [comment]
@ryanbourdais I really appreciate it!
